### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#3]
- [ ] Accept img src URL in addition to file
- [ ] Form for Width, Heigh, Quality, (and Smoothing)
- [ ] Promisify, for example
   ```js
   function blobToDataURL(blob) {
       return new Promise(function (resolve, reject) {
           var a = new FileReader();
           a.onload = function (e) {
               resolve(e.target.result);
           };
           a.onerror = function (e) {
               reject(e);
           };
           a.readAsDataURL(blob);
       });
   }
   ```

**Comment by MaxSultan** [comment]
MVP.css added July 23rd

**Comment by MaxSultan** [comment]
Basic form for width, height, quality, and smoothing added

**Comment by MaxSultan** [comment]
Promisify blobToDataUrl completed August 3rd as a part of https://github.com/MaxSultan/img-compressor/pull/15

**Comment by MaxSultan** [comment]
Copy paste added August 6th in PR https://github.com/MaxSultan/img-compressor/pull/21

**Comment by MaxSultan** [comment]
NPM/unpkg library added on August 22nd in PR https://github.com/MaxSultan/img-compressor/pull/28
